version: '3'

services:
  traefik:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    networks:
      - traefik
    extra_hosts: 
      - host.docker.internal:172.17.0.1
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=webSecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encr"
    networks:
      - traefik
networks:
  traefik:
    driver: bridge
