logLevel: INFO

log:
  level: DEBUG
  filePath: /log-file.log
  format: json

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    network: traefik
